### ISSUE TITLE
next beta release

### ISSUE THREAD

**Issue by jerch** [netzkolchose/django-computedfields#92]
beta wishlist:
- [x] type hints and sanity checks #86 
- [x] fix up pulling ambiguity #93 
- [ ] ~reduce "transactional pressure" to one transaction at top level~ _postponed_
- [x] remove multi variants #57 
- [x] ~rework transitive reduction in intermodel deps (partially done in #53)~ _dealt with in #114_
- [x] fast_update option (alpha) #97
- [x] transit to `django-fast-update` package
- [x] fix proxy models #109
- [x] F expression clarification #98 
- [x] remove obsolete optimizations (createmap & TR in intermodel graph) #114 
- [x] better update planning for `updatedata` #32 
- [ ] ~support some sort of update signals #58~ _postponed_
- [x] convenient symbol access
  - [x] place `__all__` into models.py
  - [x] make underlying graphs easier accessible from shell (lazy loading function?)
- [x] remove Django 2.2 shims 
- [x] cleanup docs (also add #90)

---

Edit: Postponed several aspects to not to delay the release too much because of only half-finished things.
